services:
  app:
    image: php:8.2-apache
    container_name: php-app
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql
      && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dpfam278@
      MYSQL_DATABASE: LoginReg
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'  # Allow root from any host
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    container_name: myapp-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Dpfam278@
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
